
const ADD_CART_ITEM = 'ADD_CART_ITEM';
const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
const REMOVE_CART_ITEMS = 'REMOVE_CART_ITEMS';
const LOAD_CART = 'LOAD_CART';

export {
    ADD_CART_ITEM,
    REMOVE_CART_ITEM,
    REMOVE_CART_ITEMS,
    LOAD_CART
};
