
const LOAD_ITEMS = 'LOAD_ITEMS';
const ADD_ITEM = 'ADD_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';
const REMOVE_ITEMS = 'REMOVE_ITEMS';
const FILTER_ITEMS = 'FILTER_ITEMS';

export {
    LOAD_ITEMS,
    ADD_ITEM,
    REMOVE_ITEM,
    REMOVE_ITEMS,
    FILTER_ITEMS
};
